# Generated by Django 5.0.6 on 2025-02-24 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "mem_time",
                    models.CharField(
                        choices=[
                            ("230", "230"),
                            ("330", "330"),
                            ("430", "430"),
                            ("530", "530"),
                            ("630", "630"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "mem_level",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("A+", "A+"),
                            ("B", "B"),
                            ("B+", "B+"),
                            ("C", "C"),
                            ("C+", "C+"),
                        ],
                        max_length=100,
                    ),
                ),
                ("total_points", models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=100)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.member"
                    ),
                ),
            ],
        ),
    ]
