# Generated by Django 5.0.6 on 2025-02-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="total_points",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
