# Generated by Django 5.0.6 on 2025-02-20 06:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="Level",
        ),
    ]
