# Generated by Django 5.0.6 on 2025-02-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="mem_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("A+", "A+"),
                    ("B", "B"),
                    ("B+", "B+"),
                    ("C", "C"),
                    ("C+", "C+"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="mem_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("230", "230"),
                    ("330", "330"),
                    ("430", "430"),
                    ("530", "530"),
                    ("630", "630"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
