# Generated by Django 5.0.6 on 2025-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
    ]
