# Generated by Django 5.0.6 on 2025-02-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_alter_member_mem_level_alter_member_mem_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="total_points",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
