# Generated by Django 5.0.6 on 2025-02-20 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_rename_group_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="group",
        ),
        migrations.AddField(
            model_name="member",
            name="group_level_mode",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="group_time_mode",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
