# Generated by Django 5.0.6 on 2025-02-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_remove_member_group_member_group_level_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="level",
            name="group_level_mode",
        ),
        migrations.RemoveField(
            model_name="level",
            name="group_time_mode",
        ),
        migrations.AddField(
            model_name="level",
            name="level",
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
