# Generated by Django 5.0.6 on 2025-02-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_alter_member_total_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="chances",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="remaining_points",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="stamps",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
