# Generated by Django 5.0.6 on 2025-02-20 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_remove_level_group_level_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="member",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.member",
            ),
            preserve_default=False,
        ),
    ]
