# Generated by Django 5.0.6 on 2025-02-27 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_member_chances_member_remaining_points_member_stamps"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="remaining_points",
            new_name="remaining_stamps",
        ),
    ]
