# Generated by Django 5.0.6 on 2025-02-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_rename_remaining_points_member_remaining_stamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="lottos",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
