# Generated by Django 5.0.6 on 2025-02-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_level_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="group_level_mode",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("A+", "A+"),
                    ("B", "B"),
                    ("B+", "B+"),
                    ("C", "C"),
                    ("C+", "C+"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="group_time_mode",
            field=models.CharField(
                choices=[
                    ("230", "230"),
                    ("330", "330"),
                    ("430", "430"),
                    ("530", "530"),
                    ("630", "630"),
                ],
                max_length=100,
            ),
        ),
    ]
