# Generated by Django 5.0.6 on 2025-02-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lottery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
