# Generated by Django 5.0.6 on 2025-02-17 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lottery", "0003_point_delete_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
