# Generated by Django 5.0.6 on 2025-02-17 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lottery", "0004_point_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="point",
            old_name="member_id",
            new_name="member",
        ),
    ]
